"""Make user_name and role_name nullable in column_permissions

Revision ID: 05bd4cb1319d
Revises: 81bb1bddaf3b
Create Date: 2025-06-19 21:59:12.625224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bd4cb1319d'
down_revision = '81bb1bddaf3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('row_permissions', 'user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('row_permissions', 'role_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('row_permissions', 'role_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('row_permissions', 'user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
