"""add updated_at to Role model

Revision ID: 112770c519e2
Revises: f3c2f110979b
Create Date: 2025-07-18 16:47:21.256011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112770c519e2'
down_revision = 'f3c2f110979b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'updated_at')
    # ### end Alembic commands ###
