"""remove role_name not null constraint from column_permissions

Revision ID: 20250717_remove_role_name_not_null
Revises: cfce6105075f
Create Date: 2025-07-17 10:39:28

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250717_rn'
down_revision = 'cfce6105075f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('column_permissions', 'role_name',
               existing_type=sa.String(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('column_permissions', 'role_name',
               existing_type=sa.String(length=50),
               nullable=False)
    # ### end Alembic commands ###
