"""make_user_role_nullable_in_table_permissions

Revision ID: 81bb1bddaf3b
Revises: cfce6105075f
Create Date: 2025-06-19 21:11:48.384081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81bb1bddaf3b'
down_revision = 'cfce6105075f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('table_permissions', 'user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('table_permissions', 'role_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('table_permissions', 'role_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('table_permissions', 'user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
