"""add update_time to permission tables

Revision ID: ba7737f4f2b9
Revises: dc4737a4d53b
Create Date: 2025-07-11 17:21:26.861222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7737f4f2b9'
down_revision = 'dc4737a4d53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_permissions', sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('row_permissions', sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('table_permissions', sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_permissions', 'update_time')
    op.drop_column('row_permissions', 'update_time')
    op.drop_column('column_permissions', 'update_time')
    # ### end Alembic commands ###
