"""Create initial tables

Revision ID: cfce6105075f
Revises: 
Create Date: 2025-06-18 21:39:08.709729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfce6105075f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('col_name', sa.String(length=100), nullable=False),
    sa.Column('mask_type', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("mask_type IN ('手机号', '身份证', '银行卡号', '座机号', '姓名', '原文')", name='check_mask_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_name', 'table_name', 'col_name', 'user_name', 'role_name', name='unique_column_permission')
    )
    op.create_index(op.f('ix_column_permissions_col_name'), 'column_permissions', ['col_name'], unique=False)
    op.create_index(op.f('ix_column_permissions_db_name'), 'column_permissions', ['db_name'], unique=False)
    op.create_index(op.f('ix_column_permissions_id'), 'column_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_column_permissions_role_name'), 'column_permissions', ['role_name'], unique=False)
    op.create_index(op.f('ix_column_permissions_table_name'), 'column_permissions', ['table_name'], unique=False)
    op.create_index(op.f('ix_column_permissions_user_name'), 'column_permissions', ['user_name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('row_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('row_filter', sa.Text(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_name', 'table_name', 'user_name', 'role_name', name='unique_row_permission')
    )
    op.create_index(op.f('ix_row_permissions_db_name'), 'row_permissions', ['db_name'], unique=False)
    op.create_index(op.f('ix_row_permissions_id'), 'row_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_row_permissions_role_name'), 'row_permissions', ['role_name'], unique=False)
    op.create_index(op.f('ix_row_permissions_table_name'), 'row_permissions', ['table_name'], unique=False)
    op.create_index(op.f('ix_row_permissions_user_name'), 'row_permissions', ['user_name'], unique=False)
    op.create_table('table_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_name', 'table_name', 'user_name', 'role_name', name='unique_table_permission')
    )
    op.create_index(op.f('ix_table_permissions_db_name'), 'table_permissions', ['db_name'], unique=False)
    op.create_index(op.f('ix_table_permissions_id'), 'table_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_table_permissions_role_name'), 'table_permissions', ['role_name'], unique=False)
    op.create_index(op.f('ix_table_permissions_table_name'), 'table_permissions', ['table_name'], unique=False)
    op.create_index(op.f('ix_table_permissions_user_name'), 'table_permissions', ['user_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='unique_user_role')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_table_permissions_user_name'), table_name='table_permissions')
    op.drop_index(op.f('ix_table_permissions_table_name'), table_name='table_permissions')
    op.drop_index(op.f('ix_table_permissions_role_name'), table_name='table_permissions')
    op.drop_index(op.f('ix_table_permissions_id'), table_name='table_permissions')
    op.drop_index(op.f('ix_table_permissions_db_name'), table_name='table_permissions')
    op.drop_table('table_permissions')
    op.drop_index(op.f('ix_row_permissions_user_name'), table_name='row_permissions')
    op.drop_index(op.f('ix_row_permissions_table_name'), table_name='row_permissions')
    op.drop_index(op.f('ix_row_permissions_role_name'), table_name='row_permissions')
    op.drop_index(op.f('ix_row_permissions_id'), table_name='row_permissions')
    op.drop_index(op.f('ix_row_permissions_db_name'), table_name='row_permissions')
    op.drop_table('row_permissions')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_column_permissions_user_name'), table_name='column_permissions')
    op.drop_index(op.f('ix_column_permissions_table_name'), table_name='column_permissions')
    op.drop_index(op.f('ix_column_permissions_role_name'), table_name='column_permissions')
    op.drop_index(op.f('ix_column_permissions_id'), table_name='column_permissions')
    op.drop_index(op.f('ix_column_permissions_db_name'), table_name='column_permissions')
    op.drop_index(op.f('ix_column_permissions_col_name'), table_name='column_permissions')
    op.drop_table('column_permissions')
    # ### end Alembic commands ###
