"""add_ldap_users_table

Revision ID: d0a2f02b27c2
Revises: 68c51f52c962
Create Date: 2025-07-18 11:48:21.013042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a2f02b27c2'
down_revision = '68c51f52c962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
