"""Add hdfs_quota table

Revision ID: dc4737a4d53b
Revises: 05bd4cb1319d
Create Date: 2025-07-11 14:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4737a4d53b'
down_revision = '05bd4cb1319d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hdfs_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=100), nullable=False),
    sa.Column('hdfs_quota', sa.Float(), nullable=False, comment='HDFS quota in GB'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hdfs_quotas_db_name'), 'hdfs_quotas', ['db_name'], unique=True)
    op.create_index(op.f('ix_hdfs_quotas_id'), 'hdfs_quotas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hdfs_quotas_id'), table_name='hdfs_quotas')
    op.drop_index(op.f('ix_hdfs_quotas_db_name'), table_name='hdfs_quotas')
    op.drop_table('hdfs_quotas')
    # ### end Alembic commands ###
