"""add_departments_table

Revision ID: f3c2f110979b
Revises: d0a2f02b27c2
Create Date: 2025-07-18 16:05:21.146330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c2f110979b'
down_revision = 'd0a2f02b27c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
